apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: {{ .Values.config.DB_HOST }}
  DB_PORT: {{ .Values.config.DB_PORT }}
  DB_NAME: {{ .Values.config.DB_NAME }}

  POSTGRES_MULTIPLE_DATABASES: {{ .Values.config.POSTGRES_MULTIPLE_DATABASES }}