apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: {{ .Values.namespace }}
spec:
  serviceName: postgres-db
  replicas: {{ .Values.statefulSet.replicas }}
  minReadySeconds: 10
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: postgres
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          envFrom:
            - configMapRef:
                name: postgres-configmap
            - secretRef:
                name: postgres-secret

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

            - name: init-script
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: init-script
          configMap:
            name: postgres-init-script
            defaultMode: 0755   

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: {{ .Values.persistentVolume.accessModes }} 
        storageClassName: payment-storageclass
        resources:
          requests:
            storage: {{ .Values.persistentVolume.storage }}