apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-db
spec:
  serviceName: payment-db
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: payment_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: payment-db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: payment-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: payment-db-storage
        resources:
          requests:
            storage: 1Gi