namespace: team3-ns

replicaCount: 1

image:
  repository: postgres
  tag: "15"

service:
  port: 5432

storage:
  size: 5Gi
  accessMode: ReadWriteOnce

storageClass:
  provisioner: nfs.csi.k8s.io
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  server: "<IP_ADDRESS>"
  share: "/exported/path"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

config:
  DB_HOST: "postgres-db"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  POSTGRES_MULTIPLE_DATABASES: "users_db,booking_db,payment_db,ticket_db"

secret:
  DB_USER: "admin"
  DB_PASSWORD: "adminpass"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "adminpass"